fix copilot suggestions

diff --git a/.github/workflows/phpcs.yml b/.github/workflows/phpcs.yml
--- a/.github/workflows/phpcs.yml
+++ b/.github/workflows/phpcs.yml
@@ -21,8 +21,8 @@ jobs:
             - name: Ensure at least one job passed
               run: |
                   if [[ "${{ needs.phpcs.result }}" == "success" ]]; then
-                      echo "Checks passed."
-                  else 
-                        echo "Checks failed."
-                        exit 1
+                    echo "Checks passed."
+                  else
+                    echo "Checks failed."
+                    exit 1
                   fi
